### ISSUE TITLE
Typing issue

### ISSUE THREAD

**Issue by Lazarus404** [haxetink/tink_chunk#14] opened 2019-11-07 19:21 UTC
When compiling `tink_http` for Java, I get:

```
haxelib/tink_chunk/0,3,0/src/tink/chunk/ByteChunk.hx:72: characters 4-14 : tink.chunk.ByteChunk should be tink.Chunk
```

**Comment by back2dos** [comment] 2019-11-09 10:48
As it is 3.0.1 passes the CI with java on both Haxe [3.4.7](https://travis-ci.org/haxetink/tink_chunk/jobs/606068490#L537) and [4.0.0](https://travis-ci.org/haxetink/tink_chunk/jobs/606068491#L557), so the issue must be specific to your build configuration. Please provide any details that could help in reproducing this ;)

**Comment by Lazarus404** [comment] 2019-11-25 08:37
So, I also get this with the CS target.  If you use the Fetch example from `tink_http`, you should see this issue.  I'm using Haxe 4.0.2

**Comment by robGetsTheJobDone** [comment] 2020-10-06 15:42
Any updates on this issue @Lazarus404 I am running into a similar issue.

**Comment by CedX** [comment] 2020-12-12 17:55
Haxe 4.1.4 (Windows x64) : same issue here with `tink_http` 0.9.1 when targeting the JVM (tested with `hxjava` 3.2.0 and 4.0.0-alpha).
The target URL is a `https` one: the underlying client is `SecureSocketClient`.

```haxe
return Client.fetch(url).noise();
// tink_chunk/0,3,1/src/tink/chunk/ByteChunk.hx:72: characters 5-15 : tink.chunk.ByteChunk should be tink.Chunk
```

**Comment by kevinresol** [comment] 2020-12-13 02:35
I guess this is fixed by https://github.com/haxetink/tink_chunk/commit/ac3430b9720765d2d842d82652a238ed20c2b52d?w=1

**Comment by CedX** [comment] 2020-12-13 13:42
Indeed, if I use the Git version of `tink_chunk`, the problem is fixed. So we just have to wait for the release of a new version on Haxelib. Thanks @kevinresol.

**Closed as completed** 2020-12-13 13:43 UTC
